name: java client test

on:
  pull_request:
    branches:
      - main

jobs:
  java-client-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: setup pulsar
        uses: shoothzj/setup-pulsar-action@v1
      - name: build kop binary
        run: cd cmd/it && go build -o kop .
      - name: run kop
        run: nohup ./cmd/it/kop >kop.log 2>&1 &
      - name: wait kop start
        uses: shoothzj/host-available-check-action@v1
        with:
          check_type: 'TCP'
          check_timeout: 60
          check_tcp_port: 9092
      - name: run java client test
        run: cd java-client-tests; mvn -B clean checkstyle:check test
      - name: print pulsar logs
        if: failure()
        continue-on-error: true
        run: docker logs pulsar
      - name: print kop logs
        if: failure()
        continue-on-error: true
        run: cat kop.log
